[alloy]
bdwgc-assertions = true

[rust]
codegen-units = 0           # Use many compilation units.
debug-assertions = true     # Turn on assertions in rustc.

[build]
docs = false
extended = true
tools = ["cargo", "rustdoc"]

[llvm]
download-ci-llvm = true

[install]
prefix = "build/rustgc-stage2-latest"
sysconfdir = "etc"
