- // MIR for `preserve_locals` before PreventEarlyFinalization
+ // MIR for `preserve_locals` after PreventEarlyFinalization
  
  | User Type Annotations
  | 0: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: Ty(General(U0)) }], value: TypeOf(DefId(5:4632 ~ alloc[4b18]::gc::{impl#5}::new), UserSubsts { substs: [^0], user_self_ty: Some(UserSelfTy { impl_def_id: DefId(5:4630 ~ alloc[4b18]::gc::{impl#5}), self_ty: std::gc::Gc<^1> }) }) } at $DIR/prevent_early_finalization.rs:14:14: 14:21
  |
  fn preserve_locals() -> () {
      let mut _0: ();                      // return place in scope 0 at $DIR/prevent_early_finalization.rs:13:22: 13:22
      let _1: std::gc::Gc<NeedsFinalize>;  // in scope 0 at $DIR/prevent_early_finalization.rs:14:9: 14:11
      let mut _2: NeedsFinalize;           // in scope 0 at $DIR/prevent_early_finalization.rs:14:22: 14:40
      scope 1 {
          debug gc => _1;                  // in scope 1 at $DIR/prevent_early_finalization.rs:14:9: 14:11
      }
  
      bb0: {
          StorageLive(_1);                 // scope 0 at $DIR/prevent_early_finalization.rs:14:9: 14:11
          StorageLive(_2);                 // scope 0 at $DIR/prevent_early_finalization.rs:14:22: 14:40
          _2 = NeedsFinalize(const 123_usize); // scope 0 at $DIR/prevent_early_finalization.rs:14:22: 14:40
          _1 = Gc::<NeedsFinalize>::new(move _2) -> [return: bb1, unwind: bb2]; // scope 0 at $DIR/prevent_early_finalization.rs:14:14: 14:41
                                           // mir::Constant
                                           // + span: $DIR/prevent_early_finalization.rs:14:14: 14:21
                                           // + user_ty: UserType(0)
                                           // + literal: Const { ty: fn(NeedsFinalize) -> std::gc::Gc<NeedsFinalize> {std::gc::Gc::<NeedsFinalize>::new}, val: Value(Scalar(<ZST>)) }
      }
  
      bb1: {
          StorageDead(_2);                 // scope 0 at $DIR/prevent_early_finalization.rs:14:40: 14:41
          FakeRead(ForLet(None), _1);      // scope 0 at $DIR/prevent_early_finalization.rs:14:9: 14:11
          _0 = const ();                   // scope 0 at $DIR/prevent_early_finalization.rs:13:22: 15:2
-         StorageDead(_1);                 // scope 0 at $DIR/prevent_early_finalization.rs:15:1: 15:2
+         nop;                             // scope 0 at $DIR/prevent_early_finalization.rs:15:1: 15:2
+         llvm_asm!(LlvmInlineAsmInner { asm: "", asm_str_style: Cooked, outputs: [], inputs: ["r"], clobbers: ["memory"], volatile: true, alignstack: false, dialect: Att } : [] : [(no-location (#0), _1)]); // scope 0 at $DIR/prevent_early_finalization.rs:15:2: 15:2
+         StorageDead(_1);                 // scope 0 at $DIR/prevent_early_finalization.rs:15:2: 15:2
          return;                          // scope 0 at $DIR/prevent_early_finalization.rs:15:2: 15:2
      }
  
      bb2 (cleanup): {
          drop(_2) -> bb3;                 // scope 0 at $DIR/prevent_early_finalization.rs:14:40: 14:41
      }
  
      bb3 (cleanup): {
          resume;                          // scope 0 at $DIR/prevent_early_finalization.rs:13:1: 15:2
      }
  }
  
